### ISSUE TITLE
Reg usage

### ISSUE THREAD

**Issue by rjeyalakshmi** [ilinsky/xpath.js#10]
Hi,
can you please let me know on how to include these files to work on XPath 2.0 expressions?
Thanks,
Jeya

**Comment by ilinsky** [comment]
Hi, do you want to run it in browser or in node?

**Comment by vasanthan07** [comment]
@ilinsky   yes, we need to run this in browser.

**Comment by ilinsky** [comment]
Should this issue still be relevant, please reopen it. Otherwise closing.
