### ISSUE TITLE
processing-instruction('foo') paths produce parse error

### ISSUE THREAD

**Issue by bedney** [ilinsky/xpath.js#5]
It seems that the engine is not parsing/executing `processing-instruction('foo')` paths properly (i.e. PIs with a custom name). I noticed the tests for this are commented out. Is this by design?

**Comment by bedney** [comment]
Moments after posting this, I did find a workaround:

`processing-instruction()[name="foo"]`

I'm not sure this returns actual results, but it does cause the parse error to go away.

**Comment by ilinsky** [comment]
Yep. Missing implementation.

**Comment by ilinsky** [comment]
Fixed per rev f6362523c064b11f58b58f9600c947d1232b2122
