### ISSUE TITLE
regular expressions  in xpath 2.0

### ISSUE THREAD

**Issue by nexus-07** [ilinsky/xpath.js#6]
Hey. Is there support for regular expressions in your library?
I tried:
document.evaluate("//*[matches(@class, 'ars')]", document, null, XPathResult.ANY_TYPE, null).iterateNext();

error:
Uncaught DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[matches(@class, 'ars')]' is not a valid XPath expression.

Thank you

**Comment by ilinsky** [comment]
In your example you are trying DOM native APIs and native XPath 1.0 
Are you interested in running code in NodeJS to in a browser? If in a browser, you should try https://github.com/ilinsky/jquery-xpath

**Comment by nexus-07** [comment]
I do not want to use the Node Js in your browser. Also, I do not want to pull the extra libraries such as jquery.

**Comment by ilinsky** [comment]
Sorry, I fail to understand you now. You were asking if regular expressions were supported in the library. Answer is yes, they are supported. Should you need further assistance, please let me know where (in a browser or in NodeJS) do you want to run the library.

**Comment by nexus-07** [comment]
I want to run in the browser.
