### ISSUE TITLE
Is this implementation of XPath 2.0 complete?

### ISSUE THREAD

**Issue by MartijnR** [ilinsky/xpath.js#8]
This looks like a very interesting project. Before looking into this deeper, is there anything missing in the implementation?

**Comment by ilinsky** [comment]
Hi Martijn, the implementation is fairly complete, to minor things I remember are missing at large: string collations, schema-attribute() / schema-element() kind tests, and element() / attribute() kind tests parameters.

**Comment by MartijnR** [comment]
Thanks!
